### ISSUE TITLE
The graph div should be made responsive.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/spectral-workbench.js#110]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

In [spectral-workbench.js](https://github.com/publiclab/spectral-workbench.js) for `capture` part we have set the graph width to `1024px` here : https://github.com/publiclab/spectral-workbench.js/blob/main/examples/capture/capture.css. But it won't work properly for every window size. We need to set the width using the media query to make it work for different screen sizes.

This is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] **🙋 Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] **📝 Update** 

  - [ ] **💾 Commit your changes**

 - [ ]  **🔀 Start a Pull Request.** There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  - [ ] **🏁 Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by sidntrivedi012** [comment]
We have a `graph` div here -
https://github.com/publiclab/spectral-workbench.js/blob/07014a8d41c98acfbe21104f6ae991e6361f7435/examples/capture/index.html#L215
This div is styled in the `capture.css` file here - 
https://github.com/publiclab/spectral-workbench.js/blob/07014a8d41c98acfbe21104f6ae991e6361f7435/examples/capture/capture.css#L40-L44
But, the graph is not yet responsive in different screen sizes. But, it can be made responsive using media queries. More on media queries here - https://css-tricks.com/snippets/css/media-queries-for-standard-devices/
Thanks 🎉  🎈 🔬 💯

**Comment by dimkov41** [comment]
Which screen sizes you want to cover? All from the published link?

**Comment by sidntrivedi012** [comment]
@dimkov41 Hey, thanks for reaching out for this fto issue.

Yes, you can try for maybe start with implementing media queries for small screen sizes like 320px and 480 px ? Having done that, you can add queries for big screen sizes of 768px and 1024 px too.

If you face any issue, feel free to ping. Thanks. 🎉 🎈 🔬 💯

**Comment by dimkov41** [comment]
I can't start project. Sorry! It can't find some module: Error: Cannot find module 'uri-js'

**Comment by sidntrivedi012** [comment]
Hey @dimkov41 , can you please share the whole error message? Also, we have to add the responsive nature to the `graph` div which is present in index.html file in the `examples/capture` directory.

**Comment by starkblaze01** [comment]
Hi, @dimkov41, have you installed node modules?. Please run
```npm i``` or ```npm install``` then restart the project.

**Comment by sidntrivedi012** [comment]
@dimkov41 Are you still working on it? Any updates?

**Comment by dimkov41** [comment]
No. I don't work on it, because I can't start the project as I told before.

> gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/dimkov/Documents/Developing/spectral-workbench.js/node_modules/contextify
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN grunt-contrib-watch@0.6.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-connect@0.8.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-jshint@0.10.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-uglify@0.5.1 requires a peer of grunt@~0.4.0 but none was installed.
npm ERR! Linux 4.15.0-54-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

**Comment by DevLukill-pl** [comment]
Is there someone working on this problem ? I am a new in contributing but i can try deal with this if i can.

**Comment by sidntrivedi012** [comment]
Hey @DevLukill-pl , please go ahead. If you get it done, do submit a patch. 

Also, if you face any problem, ping us here or on the gitter channel. Thanks.

**Comment by DevLukill-pl** [comment]
@sidntrivedi012 I have a problem with pull request. Further. I don't sure about my actions.
I updated and commited, and created a branch and now i getting this error in console " fatal: unable to access 'https://github.com/publiclab/spectral-workbench.js.git/': The requested URL returned error: 403'.

**Comment by sidntrivedi012** [comment]
@DevLukill-pl Maybe you cloned the public lab repository. Instead, you should have cloned your fork.  Can you please tell the whole error message? Or maybe a screenshot of the error and the command which leads to that error.

**Comment by DevLukill-pl** [comment]
@sidntrivedi012 Oh thanks, exactly i cloned the public lab repository. i've already made a pull request.

**Comment by discombobulateme** [comment]
Hello :) @sidntrivedi012 can I fix this issue? I understand last communication by @DevLukill-pl was 18 days ago, so don't know if we could work together or if I could give it a try?

**Comment by sidntrivedi012** [comment]
Hey @discombobulateme , I already see a PR for this issue at #132 . 

Though, don't worry there are a lot of issues where we need help. You can go to our Community Toolbox (https://code.publiclab.org) and find many first-timers-only issues there filtered by projects.

Thanks for reaching out. 🙂 🎈

**Comment by starkblaze01** [comment]
Uploaded on GCI dashboard

**Comment by SidharthBansal** [comment]
Please hide stale comments asap.
PUBLISHED ON GCI DASHBOARD

**Comment by sashadev-sky** [comment]
@SidharthBansal @starkblaze01 @sidntrivedi012 I am coonfused. There is no actual issue to solve written in the issue body?

**Comment by starkblaze01** [comment]
Hi, @sashadev-sky. I have updated the comment. Is it fine now?

**Comment by EC3x1903** [comment]
Has anybody claimed this task yet? I would be willing to take this task for GCI.

**Comment by starkblaze01** [comment]
Hi, @EC3x1903 thanks for your interest. But this task has already been taken and being solved here https://github.com/publiclab/spectral-workbench.js/pull/149.

**Comment by starkblaze01** [comment]
Merged #149
